[update]
tasks = ["interfaces", "normalize"]

[update.interfaces]
paths = ["./GithubBrowser"]
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.normalize]
paths = ["./GithubBrowser"]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["./GithubBrowser"]
duplicateKeys = true
emptyValues = true
