disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - type_name
    - line_length
    - identifier_name
    - class_delegate_protocol
    - superfluous_disable_command
    - empty_enum_arguments
function_body_length:
    - 65 # warning
    - 90 # error
type_body_length:
    - 350 # warning
    - 400 # error
file_length:
    - 500 #warning
    - 550 #error
identifier_name:
    allowed_symbols: "_"
    min_length: 2
    max_length:
        warning: 90
        error: 1000
excluded:
    - id
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
